services:
  app:
    build: .
    # container_name: steamdeck-refurbished-stock-checker
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./docker-volumes/app:/app
    