services:
  prod:
    build: .
    # container_name: steamdeck-refurbished-stock-checker
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - UID=1000
      - GID=1000
    volumes:
      - ./docker-volumes/app:/app
    
  dev:
    image: python:3.13-alpine
    restart: unless-stopped
    working_dir: /app
    environment:
      - TZ=Europe/Berlin
      - UID=1000
      - GID=1000
    volumes:
      - .:/app
    command: ["sh"]